a_threshold: 0.9
i_threshold: 0.9
len_thresh: 0
outlier_threshold: 0.5
outlier_kNN: 10
use_temporal_weight_track: False
exp_weight_rot: 0
matching: 'greedy'
alpha: 0.95
overlap: 5
every_x_frame: ${data.every_x_frame}
track_data_path: '/dvlresearch/jenny/Documents/3DOpenWorldMOT/3DOpenWorldMOT/tracks/tracks'
model: ''
split: train
track: True
convert_initial: True
register: True
initial_dets: 'initial_dets'
tracked_dets: 'tracked_dets'
registered_dets: 'registered_dets'
tracker_type: 'SimpleTracker' # 'OnlineOracleTracker'
registration_type: 'ConstICP'
out_path_for_eval: '/dvlresearch/jenny/Documents/3DOpenWorldMOT/3DOpenWorldMOT/tracks/tracks_for_eval'
max_time_track: 5 # set max_time to -1 --> take all
filter_by_width: 1000
inact_patience: 5
fixed_time: False
l_change_thresh: 0.5
w_change_thresh: 0.5
registration_len_thresh: 2
min_pts_thresh: 0
mode: 'density'
density_thresh: 0
concat: True
means_before: True
avg_w_prev: False