keep_checkpoint: False
keep_detections: False
continue_from_existing: False
eval_dir: ''
filter_moving: True
use_matched_category: False
do_corr_clustering: True
vel_evaluation: False
heuristics: False
roi_clipping: True
filter_class: 'CONVERT_ALL_TO_CARS'
inflate_bb: True
store_adapted_pseudo_labels: True
discard_last_25: False
inflation_factor: 1.0
pretty_print: True 
eval_frequency: 1
